using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using LSP.Models.TB_R_KANBAN;

namespace LSP.Models.TB_R_CONTENT_LIST
{
	public interface ITB_R_CONTENT_LIST
	{
		TB_R_CONTENT_LISTInfo TB_R_CONTENT_LIST_Get(string id);
        IList<TB_R_KANBANInfo> TB_R_CONTENT_LIST_UP_GETCURRENT_SCAN();
        IList<TB_R_KANBANInfo> TB_R_CONTENT_LIST_UP_GETCURRENT_SCAN_2();
        IList<TB_R_KANBANInfo> TB_R_CONTENT_LIST_UP_GETCURRENT_SCAN_W();
        IList<TB_R_CONTENT_LISTInfo> TB_R_CONTENT_LIST_Gets(string ID);
        IList<TB_R_CONTENT_LISTInfo> TB_R_CONTENT_LIST_GetsByOrder(TB_R_CONTENT_LISTInfo obj);
        IList<TB_R_CONTENT_LISTInfo> TB_R_CONTENT_LIST_GETS_UNLOADING_DETAILS();
        IList<TB_R_CONTENT_LISTInfo> TB_R_CONTENT_LIST_GETS_SCANNING();
        IList<TB_R_CONTENT_LISTInfo> TB_R_DAILY_ORDER_RE_GETCURRENT_SCAN();
        IList<TB_R_CONTENT_LISTInfo> TB_R_DAILY_ORDER_RE_GETCURRENT_SCAN_2(); //used for 3 all so
        IList<TB_R_CONTENT_LISTInfo> TB_R_DAILY_ORDER_RE_GETCURRENT_SCAN_4();
        IList<TB_R_CONTENT_LISTInfo> TB_R_DAILY_ORDER_RE_GETCURRENT_SCAN_5();
        IList<TB_R_CONTENT_LISTInfo> TB_R_DAILY_ORDER_RE_GETCURRENT_SCAN_5_DOCK(string SCREEN_NAME);
        
        TB_R_CONTENT_LISTInfo TB_R_DAILY_ORDER_RE_GET_QTY_ACTUAL_PLAN();

        TB_R_CONTENT_LISTInfo TB_R_DAILY_ORDER_RE_GET_QTY_ACTUAL_PLAN_TRUCK();
        TB_R_CONTENT_LISTInfo TB_R_DAILY_ORDER_RE_GET_QTY_ACTUAL_PLAN_TRUCK_DOCK(string SCREEN_NAME);

        TB_R_KANBANInfo TB_R_CONTENT_LIST_UP_GET_QTY_ACTUAL_PLAN();
        TB_R_KANBANInfo TB_R_CONTENT_LIST_UP_GET_QTY_ACTUAL_PLAN_W();
        IList<TB_R_CONTENT_LISTInfo> TB_R_CONTENT_LIST_Search(TB_R_CONTENT_LISTInfo obj);
        
		int TB_R_CONTENT_LIST_Insert(TB_R_CONTENT_LISTInfo obj);
		
		int TB_R_CONTENT_LIST_Update(TB_R_CONTENT_LISTInfo obj);

        TB_R_CONTENT_LISTInfo TB_R_CONTENT_LIST_Import(TB_R_CONTENT_LISTInfo obj);

        int TB_R_CONTENT_LIST_UPLOAD(DataTable _ContentKanban);

        int TB_R_CONTENT_LIST_MERGE();
        int TB_R_CONTENT_LIST_MERGE_V2(string GUID);
        int TB_R_CONTENT_LIST_Delete(string id);

        IList<TB_R_CONTENT_LISTInfo> TB_R_CONTENT_LIST_UP_NOT_FINISH();
        
    }
}

