import { AbpHttpInterceptor, RefreshTokenService, AbpHttpConfigurationService } from 'abp-ng2-module';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import * as ApiServiceProxies from './service-proxies';
import { ZeroRefreshTokenService } from '@account/auth/zero-refresh-token.service';
import { ZeroTemplateHttpConfigurationService } from './zero-template-http-configuration.service';

@NgModule({
    providers: [
        ApiServiceProxies.EsignSignerSearchHistoryServiceProxy,
        ApiServiceProxies.MstEsignCategoryServiceProxy,
        ApiServiceProxies.MstEsignColorServiceProxy,
        ApiServiceProxies.MstEsignActiveDirectoryServiceProxy,
        ApiServiceProxies.EsignRequestWebServiceProxy,
        ApiServiceProxies.EsignRequestServiceProxy,
        ApiServiceProxies.EsignSignerListServiceProxy,
        ApiServiceProxies.EsignActivityHistoryServiceProxy,
        ApiServiceProxies.AuditLogServiceProxy,
        ApiServiceProxies.CachingServiceProxy,
        ApiServiceProxies.ChatServiceProxy,
        ApiServiceProxies.CommonLookupServiceProxy,
        ApiServiceProxies.EditionServiceProxy,
        ApiServiceProxies.FriendshipServiceProxy,
        ApiServiceProxies.HostSettingsServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.LanguageServiceProxy,
        ApiServiceProxies.NotificationServiceProxy,
        ApiServiceProxies.OrganizationUnitServiceProxy,
        ApiServiceProxies.PermissionServiceProxy,
        ApiServiceProxies.ProfileServiceProxy,
        ApiServiceProxies.RoleServiceProxy,
        ApiServiceProxies.SessionServiceProxy,
        ApiServiceProxies.TenantServiceProxy,
        ApiServiceProxies.TenantDashboardServiceProxy,
        ApiServiceProxies.TenantSettingsServiceProxy,
        ApiServiceProxies.TimingServiceProxy,
        ApiServiceProxies.UserServiceProxy,
        ApiServiceProxies.UserLinkServiceProxy,
        ApiServiceProxies.UserLoginServiceProxy,
        ApiServiceProxies.WebLogServiceProxy,
        ApiServiceProxies.AccountServiceProxy,
        ApiServiceProxies.TokenAuthServiceProxy,
        ApiServiceProxies.TenantRegistrationServiceProxy,
        ApiServiceProxies.HostDashboardServiceProxy,
        ApiServiceProxies.PaymentServiceProxy,
        ApiServiceProxies.DemoUiComponentsServiceProxy,
        ApiServiceProxies.InvoiceServiceProxy,
        ApiServiceProxies.SubscriptionServiceProxy,
        ApiServiceProxies.InstallServiceProxy,
        ApiServiceProxies.UiCustomizationSettingsServiceProxy,
        ApiServiceProxies.PayPalPaymentServiceProxy,
        ApiServiceProxies.StripePaymentServiceProxy,
        ApiServiceProxies.DashboardCustomizationServiceProxy,
        ApiServiceProxies.WebhookEventServiceProxy,
        ApiServiceProxies.WebhookSubscriptionServiceProxy,
        ApiServiceProxies.WebhookSendAttemptServiceProxy,
        ApiServiceProxies.UserDelegationServiceProxy,
        ApiServiceProxies.DynamicPropertyServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyDefinitionServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyServiceProxy,
        ApiServiceProxies.DynamicPropertyValueServiceProxy,
        ApiServiceProxies.DynamicEntityPropertyValueServiceProxy,
        ApiServiceProxies.TwitterServiceProxy,


        // region Master eSign
        ApiServiceProxies.MstEsignDivisionServiceProxy,
        ApiServiceProxies.MstEsignDepartmentServiceProxy,
        ApiServiceProxies.MstEsignColorServiceProxy,
        ApiServiceProxies.MstEsignStatusServiceProxy,
        ApiServiceProxies.MstEsignSystemsServiceProxy,
        ApiServiceProxies.MstEsignCategoryServiceProxy,
        ApiServiceProxies.MstEsignUserImageServiceProxy,
        ApiServiceProxies.MstEsignSignerTemplateServiceProxy,
        ApiServiceProxies.MstActivityHistoryServiceProxy,
        ApiServiceProxies.MstEsignActiveDirectoryServiceProxy,
        ApiServiceProxies.MstEsignLogoServiceProxy,
        ApiServiceProxies.MstEsignEmailTemplateServiceProxy,
        ApiServiceProxies.MstEsignConfigServiceProxy,
        ApiServiceProxies.MstEsignAffiliateServiceProxy,
        // endregion Master eSign

        ApiServiceProxies.EsignRequestServiceProxy,
        ApiServiceProxies.EsignRequestWebServiceProxy,
        ApiServiceProxies.EsignDocumentListServiceProxy,
        ApiServiceProxies.EsignDocumentListWebServiceProxy,
        ApiServiceProxies.EsignCommentsServiceProxy,
        ApiServiceProxies.EsignActivityHistoryServiceProxy,
        ApiServiceProxies.EsignSignerListServiceProxy,
        ApiServiceProxies.EsignSignerTemplateLinkServiceProxy,
        ApiServiceProxies.EsignFollowUpServiceProxy,
        ApiServiceProxies.EsignReferenceRequestServiceProxy,
        ApiServiceProxies.EsignSignerNotificationServiceProxy,
        ApiServiceProxies.EsignActivityReportServiceProxy,


        { provide: RefreshTokenService, useClass: ZeroRefreshTokenService },
        { provide: AbpHttpConfigurationService, useClass: ZeroTemplateHttpConfigurationService },
        { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true },
    ],
})
export class ServiceProxyModule {}
