EXEC TB_R_PART_IN_OUT_Update
	@id ,
	@PART_ID , 
	@IS_IN_OUT ,
	@QTY ,
	@IN_OUT_BY ,
	@IN_ORDER_NO ,
	@OUT_PROD_VEHICLE_ID ,
	@IS_PROCESS_STOCK ,
	@IS_ACTIVE , 
	@CREATED_BY , 
	@CREATED_DATE , 
	@UPDATED_BY , 
	@UPDATED_DATE 
